import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
  route('robots.txt', 'routes/robots.ts'),
  route('sitemap.xml', 'routes/sitemap.ts'),
  route('llms.txt', 'routes/llms.ts'),
  route('methodology', 'routes/methodology.tsx'),
  route('developers', 'routes/developers.tsx'),
  route('a-z/:lang', 'routes/a-z.tsx'),
  route('account/login', 'routes/login.tsx'),
  route('account/register', 'routes/register.tsx'),
  route('account/watchlist', 'routes/watchlist.tsx'),
  route('advertise', 'routes/advertise.tsx'),
  route('advertise/stats/:token', 'routes/advertise-stats.tsx'),
  route('review', 'routes/review.tsx'),
  route('search/:lang', 'routes/search.tsx'),
  route('offers/:lang', 'routes/offers.tsx'),
  route('quiz/:lang', 'routes/quiz.tsx'),
  route('week/:lang', 'routes/week.tsx'),
  route('regions/:lang', 'routes/regions.tsx'),
  route('regions/:lang/:code', 'routes/region.tsx'),
  route('admin', 'routes/admin.tsx'),
  route('mailing/:action/:token', 'routes/mailing.tsx'),
  route(':lang', 'routes/lang-home.tsx'),
  route(':lang/llms.txt', 'routes/lang-llms.ts'),
  route(':lang/feed.xml', 'routes/lang-feed.ts'),
  route(':lang/daily.xml', 'routes/lang-daily-feed.ts'),
  route(':lang/:slug', 'routes/page.tsx'),
  route(':lang/:slug/llms.txt', 'routes/page-llms.ts'),
  route(':lang/:slug/feed.xml', 'routes/page-feed.ts'),
  route(':lang/:slug/edit', 'routes/page-edit.tsx'),
  route(':lang/:slug/history', 'routes/page-history.tsx'),
  route(':lang/:slug/talk', 'routes/page-talk.tsx'),
  route('*', 'routes/not-found.tsx'),
] satisfies RouteConfig;
