/**
 * Shared types for is.gratis.
 *
 * The API and the web app both import these so the shape of a page, a revision
 * and a sponsored offer is defined exactly once.
 */

/** Languages the site serves. The slug of a page is language specific. */
export const LANGUAGES = ['nl', 'en', 'de', 'es'] as const;
export type Language = (typeof LANGUAGES)[number];

/** The one-word answer every page starts with. */
export const VERDICTS = ['yes', 'no', 'usually', 'depends'] as const;
export type Verdict = (typeof VERDICTS)[number];

/** ISO 3166-1 alpha-2 country codes we accept as region keys, plus a few wider areas. */
export const REGIONS = [
  'NL', 'BE', 'DE', 'AT', 'CH', 'FR', 'ES', 'IT', 'PT', 'GB', 'IE', 'US', 'CA',
  'DK', 'NO', 'SE', 'FI', 'PL', 'LU', 'EE', 'ID', 'EU', 'WORLD',
] as const;
export type Region = (typeof REGIONS)[number];

/** Countries in the EU among the regions. */
export const EU_REGIONS: ReadonlySet<Region> = new Set<Region>(['NL', 'BE', 'DE', 'AT', 'FR', 'ES', 'IT', 'PT', 'IE', 'DK', 'SE', 'FI', 'PL', 'LU', 'EE']);

/**
 * Does something meant for one region (null: everywhere) reach a reader in another (null: any)?
 * "WORLD" reaches everyone, "EU" reaches readers in EU countries.
 */
export function regionReaches(target: Region | null, reader: Region | null): boolean {
  if (!reader || !target || target === 'WORLD' || target === reader) return true;
  return target === 'EU' && EU_REGIONS.has(reader);
}

/** Do two regions share readers, so offers for them compete for the same spots? */
export function regionsOverlap(a: Region | null, b: Region | null): boolean {
  return regionReaches(a, b) || regionReaches(b, a);
}

/** Sponsored offers a reader sees on one page at most. More cannot be booked for the same readers. */
export const OFFER_SLOTS = 3;

export interface RegionBlock {
  /** Country or area this block applies to. */
  region: Region;
  verdict: Verdict;
  /** Markdown. */
  text: string;
}

export interface SourceLink {
  title: string;
  url: string;
}

export interface Source extends SourceLink {
  /** Short id that claims cite with [^id]. */
  id: string;
}

/**
 * Why something is free, ordered from most to least free. The is.gratis scale (0 to 5) is
 * derived from it one to one, so two editors who agree on the mechanism agree on the score.
 * See FREE_TYPE_LEVEL and the methodology page.
 */
export const FREE_TYPES = ['free_good', 'collective', 'third_party', 'partial', 'exception', 'paid'] as const;
export type FreeType = (typeof FREE_TYPES)[number];

export const FREE_TYPE_LEVEL: Record<FreeType, number> = {
  free_good: 5,
  collective: 4,
  third_party: 3,
  partial: 2,
  exception: 1,
  paid: 0,
};

export const SCALE_MAX = 5;

export interface FreeScale {
  type: FreeType;
  /** The region the assessment applies to. */
  region: Region;
}

/**
 * Time price: how long someone has to work to pay for one unit. A standard measure in
 * economic history (Nordhaus 1996; Pooley and Tupy 2022). Computed, never typed in.
 */
export interface TimePrice {
  /** What one unit is, e.g. "1 liter kraanwater". */
  unit: string;
  /** Price of one unit. */
  price: number;
  /** Hourly wage used as the yardstick, in the same currency. */
  hourlyWage: number;
  currency: string;
  region: Region;
  source: SourceLink;
}

/** Seconds of work needed to pay for one unit. */
export function timePriceSeconds(timePrice: Pick<TimePrice, 'price' | 'hourlyWage'>): number {
  if (timePrice.hourlyWage <= 0) return Number.POSITIVE_INFINITY;
  return (timePrice.price / timePrice.hourlyWage) * 3600;
}

export interface Fact {
  label: string;
  value: string;
  sourceUrl?: string;
}

export interface PageImage {
  assetId: string;
  alt: string;
  width: number;
  height: number;
  credit?: string;
  /** Generated by an image model; always shown to readers. */
  ai: boolean;
}

/**
 * The structured content of one page. Stored as JSON in a revision.
 * Every text field is Markdown without raw HTML.
 */
export interface PageContent {
  verdict: Verdict;
  /** One emoji that stands for the subject. */
  emoji?: string;
  /** The subject is plural ("musea"), so its claim reads "Musea zijn gratis". */
  plural?: boolean;
  /** One or two sentences, the direct answer. Markdown. */
  summary: string;
  /** When it is free. Markdown. */
  whenFree: string;
  /** When it is not free, or what it costs instead. Markdown. */
  whenNotFree: string;
  /** Background, mechanisms and research. Markdown. */
  background: string;
  scale?: FreeScale;
  timePrice?: TimePrice;
  /** Key figures. */
  facts: Fact[];
  /** "Did you know?" items, one sentence each. Markdown. */
  trivia: string[];
  regions: RegionBlock[];
  sources: Source[];
  image?: PageImage;
}

/** Content as clients may send it and as old revisions stored it: newer fields may be missing. */
export type ContentInput = Omit<Partial<PageContent>, 'sources'> &
  Pick<PageContent, 'verdict'> & { sources?: Array<Omit<Source, 'id'> & { id?: string }> };

/** Fills fields added after a revision was written, so old revisions read like new ones. */
export function normalizeContent(content: ContentInput): PageContent {
  return {
    ...content,
    verdict: content.verdict,
    summary: content.summary ?? '',
    whenFree: content.whenFree ?? '',
    whenNotFree: content.whenNotFree ?? '',
    background: content.background ?? '',
    facts: content.facts ?? [],
    trivia: content.trivia ?? [],
    regions: content.regions ?? [],
    sources: withSourceIds(content.sources ?? []),
  };
}

export type PageStatus = 'draft' | 'published';
/** editor: the editorial language model, which checks LLM drafts and publishes them. */
export type RevisionSource = 'human' | 'llm' | 'seed' | 'editor';
export type EditorDecision = 'publish' | 'revise' | 'reject' | 'error';

export interface RevisionSummary {
  id: string;
  number: number;
  editSummary: string;
  source: RevisionSource;
  authorName: string | null;
  createdAt: string;
}

export interface Revision extends RevisionSummary {
  title: string;
  content: PageContent;
}

export interface SponsoredOffer {
  id: string;
  advertiserName: string;
  title: string;
  /** Plain text, short. What exactly is free. */
  description: string;
  url: string;
  region: Region | null;
}

/** A sponsored offer as the admin sees it, including the booking details. */
export interface SponsorBooking extends SponsoredOffer {
  lang: Language;
  slug: string;
  contactEmail: string;
  message: string | null;
  status: SponsorRequestStatus;
  /** Monthly price quoted when the request came in, in euro cents. */
  priceCents: number | null;
  startsAt: string | null;
  endsAt: string | null;
  createdAt: string;
  /** Null until the editorial language model has looked at it (or when it is switched off). */
  editor: OfferEditorAdvice | null;
  /** Booked as the only offer for these readers on the page. */
  exclusive: boolean;
  /** Approved, but not shown until the first invoice is paid. */
  awaitingPayment: boolean;
  /** Booked extra: also in the weekly mail of free offers. */
  inMailing: boolean;
  mailingPriceCents: number | null;
}

export interface Page {
  id: string;
  topicKey: string;
  lang: Language;
  slug: string;
  title: string;
  status: PageStatus;
  /** Only moderators may edit it. */
  protected: boolean;
  content: PageContent;
  currentRevision: RevisionSummary;
  sponsoredOffers: SponsoredOffer[];
  /** Result of the last automatic check of each source URL, by URL. */
  sourceChecks: Record<string, SourceCheck>;
  /** Number of visible messages on the talk page. */
  commentCount: number;
  /** Red links and automatic links for the text; see wikilinks.ts. */
  links: import('./wikilinks.js').PageLinks;
  /** Other languages this topic exists in, so the UI can link between them. */
  translations: Array<{ lang: Language; slug: string; title: string }>;
  createdAt: string;
  updatedAt: string;
}

export interface SourceCheck {
  ok: boolean;
  status: number | null;
  checkedAt: string;
}

export interface Comment {
  id: string;
  authorName: string;
  body: string;
  hidden: boolean;
  createdAt: string;
}

export interface WatchItem {
  lang: Language;
  slug: string;
  title: string;
  emoji?: string;
  revision: number;
  seenRevision: number;
  updatedAt: string;
}

/** A page as seen from one region: its verdict and text for that country. */
export interface RegionEntry {
  lang: Language;
  slug: string;
  title: string;
  emoji?: string;
  plural?: boolean;
  verdict: Verdict;
  text: string;
}

export interface SponsorQuote {
  views30: number;
  priceCents: number;
  /** Monthly extra for also being in the weekly mail of free offers. */
  mailingPriceCents: number;
  /** The region's percentage of the everywhere price. */
  regionPercent: number;
  /** Spots still free on the page right now, for readers in the asked region. */
  slotsFree: number;
  /** Monthly price to be the only offer for these readers, and whether that can be booked now. */
  exclusivePriceCents: number;
  exclusiveAvailable: boolean;
  currency: 'EUR';
}

/** A draft in the review queue. */
export interface ReviewItem extends PageListItem {
  /** Why the editorial language model left this draft for people. */
  editorNote?: string;
  createdAt: string;
  /** Claim blocks, and how many of them cite a source. */
  claims: number;
  cited: number;
  sources: number;
}

export interface PageListItem {
  lang: Language;
  slug: string;
  title: string;
  emoji?: string;
  /** For the claim, "Musea zijn gratis*". */
  plural?: boolean;
  verdict: Verdict;
  /** For the footnote under the claim. */
  scale?: FreeScale;
  status: PageStatus;
  summary: string;
  updatedAt: string;
}

export const REPORT_REASONS = ['wrong', 'outdated', 'unsourced', 'spam', 'offensive', 'copyright', 'other'] as const;
/** Reasons to report a sponsored offer: the promise of the "free here" block is broken. */
export const OFFER_REPORT_REASONS = ['not_free', 'misleading', 'offensive', 'other'] as const;
export type ReportReason = (typeof REPORT_REASONS)[number] | (typeof OFFER_REPORT_REASONS)[number];

export interface Report {
  id: string;
  lang: Language;
  slug: string;
  title: string;
  reason: ReportReason;
  message: string | null;
  status: 'open' | 'resolved';
  createdAt: string;
  /** Set when the report is about a sponsored offer on the page rather than the page itself. */
  offer?: { id: string; title: string; advertiserName: string };
}

/** Markers around the matched words in a search snippet; the web app turns them into <mark>. */
export const SNIPPET_START = '\u0002';
export const SNIPPET_END = '\u0003';

export interface SearchResult extends PageListItem {
  /** Plain text fragments around the matches, with SNIPPET_START/SNIPPET_END markers. */
  snippet: string;
}

export interface SearchResponse {
  query: string;
  results: SearchResult[];
  total: number;
  /** A page whose title looks like the query, when there are few results. */
  didYouMean: PageListItem | null;
  /** Slug of a page that matches the query exactly, if any. */
  exact: string | null;
}

/** Why a subject without a page is suggested. */
export type SuggestionReason = 'wanted' | 'searched' | 'translation' | 'starter' | 'related' | 'typed';

/** A subject that has no page yet; opening its address offers to have one written. */
export interface MissingSubject {
  slug: string;
  title: string;
  reason: SuggestionReason;
}

/** Suggestions for a query: existing pages first, then subjects without a page. */
export interface Suggestions {
  pages: PageListItem[];
  missing: MissingSubject[];
}

export interface PageWriteBody {
  title: string;
  content: PageContent;
  editSummary: string;
  /**
   * The revision the edit was based on. The API rejects the edit with 409 when the page
   * changed in the meantime. Null when creating a new page.
   */
  baseRevisionId: string | null;
}

export type DraftJobStatus = 'queued' | 'running' | 'done' | 'failed';
/** page: first version by the LLM; image: illustration; translation: a page translated into another language. */
export type DraftJobKind = 'page' | 'image' | 'translation';

export interface DraftJob {
  id: string;
  kind: DraftJobKind;
  lang: Language;
  slug: string;
  status: DraftJobStatus;
  error: string | null;
  /** For image jobs: the generated image. */
  asset: Asset | null;
  createdAt: string;
  finishedAt: string | null;
}

export interface Asset {
  id: string;
  width: number;
  height: number;
  source: 'upload' | 'ai';
}

export interface PublicConfig {
  imageGeneration: boolean;
}

export type UserRole = 'user' | 'moderator' | 'admin';

export interface User {
  id: string;
  email: string;
  displayName: string;
  role: UserRole;
}

export type SponsorRequestStatus = 'pending' | 'active' | 'rejected' | 'expired';

/**
 * Mailing lists, each subscribed to on its own. offers: this week's free offers from sponsors,
 * per region; week: the free things of the week and the new pages.
 */
export const MAILING_LISTS = ['offers', 'week'] as const;
export type MailingList = (typeof MAILING_LISTS)[number];
export type OfferEditorDecision = 'approve' | 'reject' | 'unsure';

/** The editorial language model's advice on a sponsored offer. */
export interface OfferEditorAdvice {
  decision: OfferEditorDecision;
  notes: string;
  suggestion?: { title?: string; description?: string };
  checkedAt: string;
}

export interface SponsorRequestBody {
  lang: Language;
  slug: string;
  region: Region | null;
  advertiserName: string;
  contactEmail: string;
  title: string;
  description: string;
  url: string;
  message?: string;
  /** Also in the weekly mail of free offers, for a small extra. */
  mailing?: boolean;
  /** The only offer for these readers on the page, for a higher price. */
  exclusive?: boolean;
  /** For the invoice. A VAT number from another EU country means reverse charge. */
  billingAddress?: string;
  billingCountry?: string;
  vatNumber?: string;
}

export interface ApiError {
  error: string;
  message: string;
}

/** Human readable labels per language for the verdicts. */
export const VERDICT_LABELS: Record<Language, Record<Verdict, string>> = {
  nl: { yes: 'Ja', no: 'Nee', usually: 'Meestal', depends: 'Hangt ervan af' },
  en: { yes: 'Yes', no: 'No', usually: 'Usually', depends: 'It depends' },
  de: { yes: 'Ja', no: 'Nein', usually: 'Meistens', depends: 'Kommt darauf an' },
  es: { yes: 'Sí', no: 'No', usually: 'Normalmente', depends: 'Depende' },
};

export function isLanguage(value: string): value is Language {
  return (LANGUAGES as readonly string[]).includes(value);
}

/** Slugs are lowercase letters, digits and single hyphens, max 64 chars. */
export const SLUG_PATTERN = /^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;

export function isValidSlug(value: string): boolean {
  return SLUG_PATTERN.test(value) && !value.includes('--');
}

/**
 * Picks the best language from an Accept-Language header among the available ones.
 * Returns the fallback when nothing matches. Quality values are respected.
 */
export function pickLanguage(
  header: string | null | undefined,
  available: readonly Language[] = LANGUAGES,
  fallback: Language = 'nl',
): Language {
  if (!header) return available.includes(fallback) ? fallback : (available[0] ?? fallback);
  const ranked = header
    .split(',')
    .map((part, index) => {
      const [tag = '', ...params] = part.trim().split(';');
      const q = params.map((p) => p.trim()).find((p) => p.startsWith('q='));
      const quality = q ? Number.parseFloat(q.slice(2)) : 1;
      return { lang: tag.toLowerCase().split('-')[0] ?? '', quality: Number.isNaN(quality) ? 0 : quality, index };
    })
    .filter((entry) => entry.quality > 0)
    .sort((a, b) => b.quality - a.quality || a.index - b.index);
  for (const entry of ranked) {
    const match = available.find((lang) => lang === entry.lang);
    if (match) return match;
  }
  return available.includes(fallback) ? fallback : (available[0] ?? fallback);
}

/**
 * Turns free text ("Openbaar Vervoer", "café") into a slug ("openbaar-vervoer", "cafe").
 * Returns an empty string when nothing usable is left.
 */
export function toSlug(input: string): string {
  return input
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64)
    .replace(/-+$/g, '');
}
export * from './labels.js';
export * from './markdown.js';
export * from './wikilinks.js';
export * from './brand.js';
export * from './citations.js';
export * from './starter-topics.js';
import { withSourceIds } from './citations.js';
